// packages/textfield/src/rs-textarea.vue
<template>
  <div class="rs-text-field -outlined -textarea">
    <div class="rs-text-field__form rs-text-field--textarea" ref="slotContainer" @click="activateTextArea">
    <textarea class="rs-text-field__input" v-model="value" :value="value" :maxlength="maxlength" :cols="cols" :rows="rows"
      :placeholder="placeholder" :autocomplete="autocomplete" @change="passChangeEvent" />
    </div>
    <div class="rs-notched-outline">
      <div class="rs-notched-outline__leading" />
        <div class="rs-notched-outline__notch" />
      <div class="rs-notched-outline__trailing" />
    </div>
    <div class="rs-text-field-character-counter" v-if="countable">{{ `${value.length} / ${maxlength}` }}</div>
  </div>
</template>
<script>
import { RSRipple } from '@rsmdc/ripple'

export default {
  props: {
    countable: {
      type: Boolean,
      default: false
    },
    maxlength: {
      type: String,
      default: ''
    },
    placeholder: {
      type: String,
      default: ''
    },
    autocomplete: {
      type: String,
      default: ''
    },
    dataId: {
      type: String,
      default: ''
    },
    value: {
      type: String,
      default: ''
    },
    cols: {
      type: Number,
      default: 0
    },
    rows: {
      type: Number,
      default: 0
    }
  },
  data() {
    return {
      el: '',
      host: '',
      formLabels: [],
      labelPosition: ''
    }
  },
  watch: {
    dataId() {
      this.formLabels = window.__rsmdc.formfield.formLabels.filter(formLabel => formLabel.getAttribute('data-id') === this.dataId)
      // if textfield has value, float form label.
      this.formLabels.forEach(formLabel => {
        const label = formLabel.shadowRoot.querySelector('.rs-form-label')
        if(this.value.length > 0) { 
          label.classList.add('-floatabove')
        }
        if(this.labelPosition) {
          label.style.setProperty('--rs-form-label__textarea__floatinglabel--left', this.labelPosition)
        }
      })
    },
    el() {
      this.host = this.el.parentNode.host
    },
    host() {
      window.__rsmdc.textfield.textareas.push(this.host)
      this.labelPosition = this.getElementProperty(this.host, '--rs-form-label__textarea__floatinglabel--left')
    }
  },
  created() {
    if(!window.__rsmdc) {
      window.__rsmdc = {}
    }
    if(!window.__rsmdc.textfield) {
      window.__rsmdc.textfield = {
        textfields: [],
        textareas: []
      }
    }
  },
  mounted() {
    const ripple = new RSRipple(this.$el.querySelector('.rs-text-field__form'))
    this.el = this.$el
  },
  methods: {
    getElementProperty(el, prop) {
      const style = window.getComputedStyle(el)
      const value = String(style.getPropertyValue(prop)).trim()
      return value
    },
    passChangeEvent(event) {
      this.$emit('change', event.target.value)
    },
    activateTextArea() {
      if(this.formLabels.length === 0) {
        this.formLabels = window.__rsmdc.formfield.formLabels.filter(formLabel => formLabel.getAttribute('data-id') === this.dataId)
      }
      this.changeLabelStyle('activate')
      this.el.classList.add('-floatabove')
      this.activateRipple()

      this.el.classList.add('-focus')
      this.el.querySelector('.rs-text-field__input').focus()
      this.host.addEventListener('blur', () => {
        this.el.classList.remove('-focus')
        this.deactivateTextField()
      })
    },
    deactivateTextField() {
      this.changeLabelStyle('deactivate')
      if(this.value.length === 0) {
        this.el.classList.remove('-floatabove')
      }
      this.deactivateRipple()
    },
    activateRipple() {
      this.el.querySelector('.rs-text-field__form').classList.add('rs-ripple-upgraded--background-focused')
    },
    deactivateRipple() {
      this.el.querySelector('.rs-text-field__form').classList.remove('rs-ripple-upgraded--background-focused')
    },
    changeLabelStyle(state) {
      if(state == 'activate') {
        // float form label to above and focus
        this.formLabels.forEach(formLabel => {
          const label = formLabel.shadowRoot.querySelector('.rs-form-label')
          this.setLabelWidth(label)
          label.click()
          label.classList.add('-floatabove')
          label.classList.add('-focus')
          label.classList.remove('-shake')
        })
      } else {
        // remove label focus ( and if textfield does not input anyting, sink label)
        this.formLabels.forEach(formLabel => {
          const label = formLabel.shadowRoot.querySelector('.rs-form-label')
          label.classList.remove('-focus')
          if(this.value.length === 0) {
            label.classList.remove('-floatabove')
            this.el.classList.remove('-floatabove')
          } else {
            this.el.classList.add('-floatabove')
          }
          // only error
          if(this.value.length > 0 && label.classList.contains('-invalid')) {
            label.classList.add('-shake')
          }     
        })
      }
    },
    setLabelWidth(label) {
      const labelWidth = this.getElementProperty(label, 'width')
      if(!labelWidth) { return }
      const width = parseInt(labelWidth.replace('px', '')) * 0.75 + 8
      this.el.querySelector('.rs-notched-outline__notch').style.setProperty('--rs-text-field__outlined-notched-outline-notch--width', `${width}px`)
    }
  }
}
</script>

<style lang="scss">
@import "../mixins";
@import "../character-counter/mixins";
@import "@rsmdc/notched-outline/mixins";
@import "@rsmdc/line-ripple/rs-line-ripple";

.rs-text-field__form.rs-text-field--textarea {
  @include rs-text-field-form_;

  display: inline-flex;
  width: auto;
  height: auto;
  transition: none;
  resize: auto;

  .-disabled & {
    background-color: $rs-textarea-disabled-background;
    border-bottom: none;
  }

  :not(.-disabled) & {
    background-color: var(--rs-text-field_not__disabled-form__textarea--background-color, transparent);
  }

  &::before {
    background-color: var(--rs-text-field-form__textarea__before--background-color, transparent);
  }

  > .rs-text-field__input {
    $padding-inset: 16px;

    align-self: auto;
    box-sizing: border-box;
    height: auto;
    margin: $padding-inset/2 1px 1px 0;
    padding: 0 $padding-inset $padding-inset;
    border: none;
  }
}

.rs-text-field__input {
  @include rs-text-field-input_;
}

.rs-line-ripple {
  @include rs-text-field-line-ripple-color(primary);

  .-invalid & {
    @include rs-text-field-line-ripple-color($rs-text-field-error);
  }

  .-outlined & {
    display: none;
  }
}

.rs-text-field-character-counter {
  @include rs-text-field-character-counter_;
  
  padding-bottom: 0;
  position: absolute;
  bottom: var(--rs-text-field-character-counter--bottom, 13px);
  right: var(--rs-text-field-character-counter--right, 16px);
}

.rs-notched-outline {
  @include rs-notched-outline_;
}


.rs-notched-outline__leading {
  @include rs-notched-outline-leading_;
}

.rs-notched-outline__notch {
  @include rs-notched-outline-notch_;
}

.rs-notched-outline__trailing {
  @include rs-notched-outline-trailing_;
}

</style>

// packages/textfield/src/components/rs-textfield/rs-textarea.tsx
import { Component, Element, Prop, Watch, Event, EventEmitter, Method, Host, h } from '@stencil/core'
import { RSRipple } from '@rsmdc/ripple'
import { RSLineRipple } from '@rsmdc/line-ripple'

@Component({
  tag: 'rs-textarea',
  styleUrl: '../../dist/result.css',
  shadow: true
})
export class Textarea {

  @Element() el: HTMLElement

  @Prop() label: string

  @Prop() disabled: boolean

  @Prop() invalid: boolean

  @Prop() required: boolean

  @Prop() countable: boolean

  @Prop() type: string = 'text'

  @Prop() value: string = ''

  @Prop() placeholder: string = ''

  @Prop() maxlength: string = ''

  @Prop() cols: number

  @Prop() rows: number


  textarea: Element

  labels: Element[]

  nativeControl: Element

  htmlNativeConctrol: HTMLSelectElement

  notch: HTMLElement

  counter: Element

  rsRipple: RSRipple

  rsLineRipple: RSLineRipple

  @Event({
    cancelable: false,
    composed: false,
  }) change: EventEmitter

  @Watch('disabled')
  disabledHandler() {
    this.isDisabled()
  }

  @Watch('invalid')
  invalidHandler() {
    this.isInvalid()
  }

  @Watch('required')
  requiredHandler() {
    this.isRequired()
  }

  @Watch('countable')
  countableHandler() {
    this.isCountable()
  }

  @Method()
  async isDisabled() {
    if (this.disabled) {
      this.textarea.classList.add('-disabled')
    } else {
      this.textarea.classList.remove('-disabled')
    }
  }

  @Method()
  async isInvalid() {
    if (this.invalid) {
      this.textarea.classList.add('-invalid')
    } else {
      this.textarea.classList.remove('-invalid')
    }
  }

  @Method()
  async isRequired() {
    if (this.required) {
      this.textarea.classList.add('-required')
    } else {
      this.textarea.classList.remove('-required')
    }
  }

  @Method()
  async isCountable() {
    if (this.countable) {
      this.counter.classList.remove('-hidden')
    } else {
      this.counter.classList.add('-hidden')
    }
  }

  @Method()
  async floatLabel() {
    this.labels.forEach(l => { 
      l.classList.add('-floatabove')
    })
    this.setLabelWidthToNotch()
  }

  @Method()
  async setLabelWidthToNotch() {
    const labelWidth = await this.retriveLabelWidth(this.labels)
    const width = labelWidth * 0.75 + 8
    this.notch.style.setProperty('width', `${width}px`)
  }

  @Method()
  async addFocusStyle() {
    this.textarea.classList.add('-focused')
    this.textarea.classList.add('rs-ripple-upgraded--background-focused')
    this.rsLineRipple.activate()
    this.labels.forEach(l => { 
      l.classList.add('-floatabove')
      this.notch.classList.add('-border')
      if (!l.classList.contains('-shake')) { return }
      l.classList.remove('-shake')
    })
    this.setLabelWidthToNotch()
  }

  @Method()
  async removeFocusStyle() {
    this.textarea.classList.remove('-focused')
    this.textarea.classList.remove('rs-ripple-upgraded--background-focused')
    this.rsLineRipple.activate()

    this.labels.forEach(l => {
      if (this.invalid && this.value) l.classList.add('-shake')
      if (this.value) return
      l.classList.remove('-floatabove')
      this.notch.classList.remove('-border')
      this.notch.style.setProperty('--width', 'auto')
    })
  }

  @Method()
  async retriveLabelWidth(labels) {
    return labels.reduce((res, l) => {
      return res > l.clientWidth
        ? res
        : l.clientWidth
    }, 0)
  }

  @Method()
  async changeHandler() {
    this.value = this.htmlNativeConctrol.value

    this.change.emit({ value: this.value })
  }

  componentDidLoad() {
    this.textarea = this.el.shadowRoot.querySelector('.rs-textfield')
    this.labels = Array.from(this.el.shadowRoot.querySelectorAll('.label'))
    this.nativeControl = this.el.shadowRoot.querySelector('.input')
    this.htmlNativeConctrol = (this.nativeControl as HTMLSelectElement)
    this.notch = this.el.shadowRoot.querySelector('.notch')
    this.counter = this.el.shadowRoot.querySelector('.counter')
    this.rsLineRipple = new RSLineRipple(this.el.shadowRoot.querySelector('.rs-line-ripple'))
    this.rsRipple = new RSRipple(this.textarea)
    
    this.isDisabled()
    this.isInvalid()
    this.isRequired()
    this.isCountable()
    
    this.nativeControl.addEventListener('focus', () => {
      this.addFocusStyle()
    })

    this.nativeControl.addEventListener('change', () => {
      this.changeHandler()
    })

    this.nativeControl.addEventListener('blur', () => {
      this.removeFocusStyle()
    })
    
    this.nativeControl.addEventListener('keyup', () => {
      this.value = this.htmlNativeConctrol.value
    })
  }

  componentDidUnLoad() {
    this.nativeControl.removeEventListener('focus', () => {
      this.addFocusStyle()
    })

    this.nativeControl.removeEventListener('change', () => {
      this.changeHandler()
    })

    this.nativeControl.removeEventListener('blur', () => {
      this.removeFocusStyle()
    })

    this.nativeControl.removeEventListener('keyup', () => {
      this.value = this.htmlNativeConctrol.value
    })
  }

  render() {
    return  <Host>
              <div class="rs-textfield -outlined -textarea">
                <div class="form -textarea">
                  <textarea class="input" cols={this.cols} rows={this.rows} placeholder={this.placeholder} maxlength={this.maxlength} />
                </div>
                <div class="rs-line-ripple -none" />
                <div class="outline -area">
                  <div class="leading" />
                  <div class="notch">
                    <label class="label -outlined">{ this.label }</label>
                  </div>
                  <div class="trailing" />
                </div>
                <div class="counter -none -textarea">{ `${this.value.length} / ${this.maxlength}` }</div>
              </div>
            </Host>
  }
}
